// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8rhtNxDYHiZX8Q-S5u-GRhDu1Mev0594',
    appId: '1:1052311756861:web:794692fbe1a2a016238a54',
    messagingSenderId: '1052311756861',
    projectId: 'cauping-8df9f',
    authDomain: 'cauping-8df9f.firebaseapp.com',
    storageBucket: 'cauping-8df9f.firebasestorage.app',
    measurementId: 'G-BR2E1QXQHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4SX4IOUjV7CDrsavCHGv0y6J1uW_GtcQ',
    appId: '1:1052311756861:android:6fb581e8ff6f57ad238a54',
    messagingSenderId: '1052311756861',
    projectId: 'cauping-8df9f',
    storageBucket: 'cauping-8df9f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8rhtNxDYHiZX8Q-S5u-GRhDu1Mev0594',
    appId: '1:1052311756861:web:2b1eb10b9d7df523238a54',
    messagingSenderId: '1052311756861',
    projectId: 'cauping-8df9f',
    authDomain: 'cauping-8df9f.firebaseapp.com',
    storageBucket: 'cauping-8df9f.firebasestorage.app',
    measurementId: 'G-JGZSK4J4EH',
  );
}
